/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.Jorge.wordle.gui;

/**
 *
 * @author alumno
 */
public class ajustesPanelGui extends javax.swing.JDialog {

    /**
     * Creates new form ajustesPanelGui
     */
    public ajustesPanelGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjPanel1 = new javax.swing.JPanel();
        cuerpojPanel = new javax.swing.JPanel();
        anadirjPanel = new javax.swing.JPanel();
        insertarjPanel = new javax.swing.JPanel();
        anadirjTextField = new javax.swing.JTextField();
        anadirjButton = new javax.swing.JButton();
        estadoInsertarjPanel = new javax.swing.JPanel();
        estadoInsertarjLabel = new javax.swing.JLabel();
        borrarjPanel = new javax.swing.JPanel();
        borradojPanel = new javax.swing.JPanel();
        borrarjTextField = new javax.swing.JTextField();
        borrarjButton = new javax.swing.JButton();
        estadoBorradojPanel = new javax.swing.JPanel();
        estadoBorrarjLabel = new javax.swing.JLabel();
        titulojPanel = new javax.swing.JPanel();
        titulojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainjPanel1.setLayout(new java.awt.BorderLayout());

        cuerpojPanel.setLayout(new java.awt.GridLayout());

        anadirjPanel.setLayout(new java.awt.GridLayout());

        anadirjTextField.setText("jTextField1");
        insertarjPanel.add(anadirjTextField);

        anadirjButton.setText("jButton1");
        insertarjPanel.add(anadirjButton);

        anadirjPanel.add(insertarjPanel);

        estadoInsertarjPanel.setLayout(new java.awt.GridBagLayout());

        estadoInsertarjLabel.setText("jLabel1");
        estadoInsertarjPanel.add(estadoInsertarjLabel, new java.awt.GridBagConstraints());

        anadirjPanel.add(estadoInsertarjPanel);

        cuerpojPanel.add(anadirjPanel);

        borrarjPanel.setLayout(new java.awt.GridLayout());

        borrarjTextField.setText("jTextField1");
        borradojPanel.add(borrarjTextField);

        borrarjButton.setText("jButton1");
        borradojPanel.add(borrarjButton);

        borrarjPanel.add(borradojPanel);

        estadoBorradojPanel.setLayout(new java.awt.GridBagLayout());

        estadoBorrarjLabel.setText("jLabel1");
        estadoBorradojPanel.add(estadoBorrarjLabel, new java.awt.GridBagConstraints());

        borrarjPanel.add(estadoBorradojPanel);

        cuerpojPanel.add(borrarjPanel);

        titulojPanel.setLayout(new java.awt.GridBagLayout());

        titulojLabel.setText("jLabel1");
        titulojPanel.add(titulojLabel, new java.awt.GridBagConstraints());

        cuerpojPanel.add(titulojPanel);

        mainjPanel1.add(cuerpojPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajustesPanelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajustesPanelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajustesPanelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajustesPanelGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ajustesPanelGui dialog = new ajustesPanelGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirjButton;
    private javax.swing.JPanel anadirjPanel;
    private javax.swing.JTextField anadirjTextField;
    private javax.swing.JPanel borradojPanel;
    private javax.swing.JButton borrarjButton;
    private javax.swing.JPanel borrarjPanel;
    private javax.swing.JTextField borrarjTextField;
    private javax.swing.JPanel cuerpojPanel;
    private javax.swing.JPanel estadoBorradojPanel;
    private javax.swing.JLabel estadoBorrarjLabel;
    private javax.swing.JLabel estadoInsertarjLabel;
    private javax.swing.JPanel estadoInsertarjPanel;
    private javax.swing.JPanel insertarjPanel;
    private javax.swing.JPanel mainjPanel1;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JPanel titulojPanel;
    // End of variables declaration//GEN-END:variables
}
